global:
  params:
    a: 11
    b: 22

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      client:
        url: http://localhost:8090