customer:
  params:
    x: 22
    y: 33

server:
  port: 8081

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/customer
    password: 172002
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
